Write to file in binary mode
Since we're writing bytes, write in binary mode.
Fixes error: 
```
Traceback (most recent call last):
  File "backup.py", line 103, in <module>
    if parse_and_save_message(message) and args.delete:
  File "backup.py", line 72, in parse_and_save_message
    f.write(email.as_bytes())
TypeError: write() argument must be str, not bytes
```